#@hostname= https://miun-sampi-database-96bc66384ce1.herokuapp.com/api 
@hostname= http://localhost:8000/api
#@token=11|X3am8DA0m7iCbYmuN8smb33LOGu64BXAXELAHejG

# Adding a new controller: make sure that the file is imported into the routes (api.php) file.

GET {{hostname}}/changes

###

POST {{hostname}}/changes
Content-Type: application/json

{
    "word_id": 3,
    "message": "this is a test",
    "name": "Natalie", 
    "email": "natalie@mbp.se",
    "telephone": "0730 56 79 67",
    "status": null,
    "checked_by": null
}


###


GET {{hostname}}/words/search/g

###






